database:
  driver: 'mysql'
  host: '127.0.0.1'
  port: 3306
  database: 'orderSystem'
  username: 'root'
  password: '123456'
  charset: 'utf8mb4'
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: 'info'
  enable_file_log_writer: true
  log_filename: 'sql.log'
log:
  level: 'info'
  root_dir: './storage/logs'
  filename: 'app.log'
  format: ''
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true
redis:
  host: '127.0.0.1'
  port: 6379
  db: 0
  password: ''